#################################################################
#						RandomEvents							#
#						Configuration							#
#################################################################

secondsTimer: 60

probabilityRandomEvent: 5

minPlayers: 40

commandsOnUserJoin:
- 'psa %player%'

spawn:
  ==: org.bukkit.Location
  world: world
  x: 0.0
  y: 60.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0


