#################################################################
#						RandomEvents							#
#						Configuration							#
#################################################################

debugMode: false

#Seconds to check if the probability match for a random event
secondsTimer: 60

#Seconds to check if the minimum players is fulfilled to begin the match
secondsCheckPlayers: 15

#Minimum amount of players to begin checking for random events
minPlayers: 40

# Percentage of probability to spawn a random event each time the timer is fired
probabilityRandomEvent: 5

#Probability that the spawned random event is a tournament
probabilityRandomEventTournament: 5

#Teleport to the last location instead of spawn of the plugin
useLastLocation: false

#Number of annoucements the random event will do before being cancelled for lack of players
numberOfTriesBeforeCancelling: 10

#Advanced spectator mode
advancedSpectatorMode: false

#Force Empty Inventory to Join the RandomEvents
forceEmptyInventoryToJoin: false

#CAUTION. IT IS HIGHLY RECOMMENDED to let it true. If false, the plugin will not manage the items so players will join with own items and can lose them there.
#Some minigames might not work if its set to false (Splegg, TNT Tag...) as they need special items to work
inventoryManagement: true

#Drops items after dying in a minigame
dropItemsAfterDie: false

#Number of gems to win in gem crawler minigame
numberOfGems: 10

#Number of seconds you have to save the gems to win in gem crawler minigame
numberOfSecondsWithGems: 10

#Seconds to begin TNT_RUN so TNT will begin to disappear
warmupTimeTNTRUN: 5

#Seconds to begin the match when the min players are fulfilled (minimum 3 seconds)
secondsToStartMatch: 5

#Highest priority level of events. Enable this to bypass damage protection of faction plugins for example.
highestPriorityDamageEvents: false

#Optional titles for some messages such as the seconds remaining to begin a match, turn this to true if you want to see titles instead of messages in chat.
optionalTitles: false

#Maximum items in chests on Survival Games or Skywars minigames
maxItemOnChests: 10

#Minimum items in chests on Survival Games or Skywars minigames
minItemOnChests: 3

#Show world border in some minigames
showBorders: false

#Use scoreboard in some minigames
useScoreboard: true

#Use particles in some minigames
useParticles: false

#Allowed configurable particles ->
#EXPLOSION_NORMAL  || EXPLOSION_LARGE    ||  EXPLOSION_HUGE    ||  FIREWORKS_SPARK
#WATER_BUBBLE      || WATER_SPLASH       ||  WATER_WAKE        ||  SUSPENDED
#SUSPENDED_DEPTH   || CRIT               ||  CRIT_MAGIC        ||  SMOKE_NORMAL
#SMOKE_LARGE       || SPELL              ||  SPELL_INSTANT     ||  SPELL_MOB
#SPELL_MOB_AMBIENT || SPELL_WITCH        ||  DRIP_WATER        ||  DRIP_LAVA
#VILLAGER_ANGRY    || VILLAGER_HAPPY     ||  TOWN_AURA         ||  NOTE
#PORTAL            || ENCHANTMENT_TABLE  ||  FLAME             ||  LAVA
#CLOUD             || REDSTONE           ||  SNOWBALL          ||  SNOW_SHOVEL
#SLIME             || HEART              ||  BARRIER           ||  ITEM_CRACK
#BLOCK_CRACK       || BLOCK_DUST         ||  WATER_DROP        ||  MOB_APPEARANCE
#DRAGON_BREATH     || END_ROD            ||  DAMAGE_INDICATOR  ||  SWEEP_ATTACK
particleDeath: 'EXPLOSION_NORMAL'
particleTNTTag: 'REDSTONE'

#Particles forms:
#blackSun(radius, radiusRate, rate, rateChange)    
#circle(radius, rate)                               
#crescent(radius, rate)                            
#cylinder(height, radius, rate)                      
#diamond(radiusRate, rate, height)                   
#ellipse(radius, radius2, rate)                  
#eye(radius, radius2, rate, extension)              
#filledCircle(radius, rate, radiusRate)              
#illuminati(size, extension)                        
#infinity(radius, rate)                             
#ring(rate, radius, radius2)                      
#sphere(radius, rate)                                
#meguminExplosion(size)    
#Use RANDOM to spawn one of the effects at a time randomly    
particle:
  type: sphere
  size: 1.0
  radius: 1.0
  radiusRate: 1.0
  radius2: 1.0
  rate: 4.0
  rateChange: 1.0
  height: 1.0
  extension: 4.0

tournament:
  spawn:
    world: world
    x: 0.0
    y: 60.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0
  maxPlayers: 64
  minPlayers: 20
  numberOfRounds: 5
  rewards:
      - 'eco give %player% 10000'

#Probability to spawn a power up of resistance in arrow rain games
probabilityPowerUp: 1

#Seconds for several minigames to damage all players if they are not attacking each other
idleTimeForDamage: 10

#Item material for checkpoint item
checkpointItem: 'BLAZE_ROD'

#Arrow damage in arrow rain minigame
arrowRainDamage: 10

#Enable this to make a player lose when they fall into water in knockback duel minigames
waterKillKnockbackDuel: false

#Lvl of the speed for the runners on tnttag
tntTagSpeedRunners: 3

#Lvl of the speed for the holder of the tnt on tnttag
tntTagSpeedHolder: 6

#Heal killer after a kill in OITC Minigame
oitcHealAfterKill: true

#Heal killer after a kill in Top Killer Minigame
topKillerHealAfterKill: true

#Cooldown before respawning again in minigames with respawn
cooldownAfterDeath: false

#Force the players to enter the random event when its spawned
forcePlayersToEnter: false

#Commands that will be done each time a user join a random event, use it in case you need to get the god mode off, to set the gamemode to survival, etc
commandsOnUserJoin:
- 'psa %player%'

#Commands that will be done each time a user leave a random event, use it in case you need to get the god mode off, to set the gamemode to survival, etc
commandsOnUserLeave:
- 'psa %player%'

#Commands that will be done when the match begin for all players, use it in case you need to get the god mode off, to set the gamemode to survival, etc
commandsOnMatchBegin:
- 'god %player% off'

#Commands that will be done when the match ends
commandsOnMatchEnd:
- 'broadcast %event% has ended'

#Allowed cmds in matchs. (DONT USE CAPS HERE)
allowedCmds:
- msg
- ac
- revent
- randomevent


#Spawn where the player will be teleported after minigame ends
spawn:
  world: world
  x: 0.0
  y: 60.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0
  
#Use -1 to hide a stat in the GUI
statsmenu:
  fill: 'STAINED_GLASS_PANE'
  ALLTIME: 4
  BR: 10
  BRT2: 11
  LJ: 12
  TKLL: 13
  TKLLT2: 14
  KBD: 15
  EARR: 16
  GEMC: 19
  BOMB: 20
  BOAT_RUN: 21
  HORSE_RUN: 22
  ESCAPE_FROM_BEAST: 23
  RACE: 24
  TNTRUN: 25
  SPLEEF: 28
  SPLEGG: 29
  OITC: 30
  SG: 31
  TSG: 32
  SW: 33
  TSW: 34
  ANVIL_SPLEEF: 39
  WDROP: 41

#Enable MySQL to have statistics of the games!
mysql:
  enabled: false
  UUIDMode: false
  host: localhost
  port: 3306
  database: database
  username: user
  password: password


