name: RandomEvents
main: com.adri1711.randomevents.RandomEvents
version: 1.9.4.8
api-version: 1.13
depend: [Lib1711]
softdepend: [CrackShot, PlaceholderAPI, WorldEdit, WorldGuard, Multiworld, Multiverse-Core]
commands:
   revent:
      description: Shows the command menu too
      usage: /revent
   randomevent:
      description: Shows the command menu too
      usage: /randomevent