name: RandomEvents
main: com.adri1711.randomevents.RandomEvents
version: 1.6.9
depend: [Lib1711]
softdepend: [CrackShot, PlaceholderAPI]
commands:
   revent:
      description: Shows the command menu too
      usage: /revent
   randomevent:
      description: Shows the command menu too
      usage: /randomevent